version: '2.1'

services:

  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        - YII_ENV=${YII_ENV}
    image: 'app_test:1.0'
    env_file:
      - .env
      - .env.local
    ports:
      - ${APP_PORT:-80}:80
    volumes:
      - .:/app:delegated
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
      - .env.local
